name: Build and Test with Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release

  test-and-coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Test
        run: dotnet test --configuration Release --collect:"XPlat Code Coverage" --settings coverlet.runsettings

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.10.12

      - name: Generate coverage report
        run: reportgenerator -reports:'**/coverage.cobertura.xml' "-targetdir:TestResults/CoverageReport" "-reporttypes:Html,Badges;"

      - name: Upload coverage report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          fail-on-upload-error: true

      - name: Deploy coverage report
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PTA }}
          publish_dir: ./TestResults/CoverageReport
          publish_branch: gh-pages
          commit_message: "Update code coverage report"